name: flutter_walking_in_bangkok
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.0.0
  intl: ^0.19.0
  url_launcher: ^6.1.11
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.2.0
  page_transition: ^2.0.9
  form_field_validator: ^1.1.0
  date_field: ^5.2.1
  html: ^0.15.4
  flutter_secure_storage: ^8.0.0
  pull_to_refresh: ^2.0.0
  badges: ^3.1.1
  share_plus: ^7.0.2
  package_info_plus: ^4.0.2
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  flutter_map_animations: ^0.5.3
  permission_handler: ^10.4.0
  geolocator: ^9.0.2
  geocoding: ^2.1.1
  fluttertoast: ^8.2.2
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_icon.png"

  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
